// <auto-generated />
using System;
using APBDpk2.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBDpk2.Migrations
{
    [DbContext(typeof(MuzykaDbContext))]
    [Migration("20230606211534_Migracja2")]
    partial class Migracja2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBDpk2.Entities.Album", b =>
                {
                    b.Property<int>("IdAlbum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlbum"));

                    b.Property<DateTime>("DataWydania")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdWytwornia")
                        .HasColumnType("int");

                    b.Property<string>("NazwaAlbumu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdAlbum")
                        .HasName("Album_pk");

                    b.HasIndex("IdWytwornia");

                    b.ToTable("Album", (string)null);
                });

            modelBuilder.Entity("APBDpk2.Entities.Muzyk", b =>
                {
                    b.Property<int>("IdMuzyk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMuzyk"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Pseudonim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMuzyk")
                        .HasName("Muzyk_pk");

                    b.ToTable("Muzyk", (string)null);
                });

            modelBuilder.Entity("APBDpk2.Entities.Utwor", b =>
                {
                    b.Property<int>("IdUtwor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtwor"));

                    b.Property<int?>("AlbumIdAlbum")
                        .HasColumnType("int");

                    b.Property<DateTime>("CzasTrwania")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdAlbum")
                        .HasColumnType("int");

                    b.Property<string>("NazwaUtworu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdUtwor")
                        .HasName("Utwor_pk");

                    b.HasIndex("AlbumIdAlbum");

                    b.HasIndex("IdAlbum");

                    b.ToTable("Utwor", (string)null);
                });

            modelBuilder.Entity("APBDpk2.Entities.WykonawcaUtworu", b =>
                {
                    b.Property<int>("IdMuzyk")
                        .HasColumnType("int");

                    b.Property<int>("IdUtwor")
                        .HasColumnType("int");

                    b.HasKey("IdMuzyk", "IdUtwor")
                        .HasName("WykonawcaUtworu_pk");

                    b.HasIndex("IdUtwor");

                    b.ToTable("Wykonawca_Utworu", (string)null);
                });

            modelBuilder.Entity("APBDpk2.Entities.Wytwornia", b =>
                {
                    b.Property<int>("IdWytwornia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWytwornia"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdWytwornia")
                        .HasName("Wytwornia_pk");

                    b.ToTable("Wytwornia", (string)null);
                });

            modelBuilder.Entity("APBDpk2.Entities.Album", b =>
                {
                    b.HasOne("APBDpk2.Entities.Wytwornia", "wytwornia")
                        .WithMany("Album")
                        .HasForeignKey("IdWytwornia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Wytwornia_fk");

                    b.Navigation("wytwornia");
                });

            modelBuilder.Entity("APBDpk2.Entities.Utwor", b =>
                {
                    b.HasOne("APBDpk2.Entities.Album", null)
                        .WithMany("utwor")
                        .HasForeignKey("AlbumIdAlbum");

                    b.HasOne("APBDpk2.Entities.Album", "Album")
                        .WithMany()
                        .HasForeignKey("IdAlbum")
                        .HasConstraintName("UtworAlbum_fk");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("APBDpk2.Entities.WykonawcaUtworu", b =>
                {
                    b.HasOne("APBDpk2.Entities.Muzyk", "Muzyk")
                        .WithMany("wykonawcaUtworu")
                        .HasForeignKey("IdMuzyk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBDpk2.Entities.Utwor", "utwor")
                        .WithMany("wykonawcaUtworu")
                        .HasForeignKey("IdUtwor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muzyk");

                    b.Navigation("utwor");
                });

            modelBuilder.Entity("APBDpk2.Entities.Album", b =>
                {
                    b.Navigation("utwor");
                });

            modelBuilder.Entity("APBDpk2.Entities.Muzyk", b =>
                {
                    b.Navigation("wykonawcaUtworu");
                });

            modelBuilder.Entity("APBDpk2.Entities.Utwor", b =>
                {
                    b.Navigation("wykonawcaUtworu");
                });

            modelBuilder.Entity("APBDpk2.Entities.Wytwornia", b =>
                {
                    b.Navigation("Album");
                });
#pragma warning restore 612, 618
        }
    }
}
